// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package pgstore

import (
	"context"
	"time"
)

const getDocument = `-- name: GetDocument :one
SELECT id, owner_id, title, created_at, updated_at
FROM documents
WHERE id = $1
`

type GetDocumentRow struct {
	ID        string
	OwnerID   string
	Title     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetDocument(ctx context.Context, id string) (GetDocumentRow, error) {
	row := q.db.QueryRowContext(ctx, getDocument, id)
	var i GetDocumentRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocumentsByOwner = `-- name: ListDocumentsByOwner :many
SELECT id, owner_id, title, created_at, updated_at
FROM documents
WHERE owner_id = $1
ORDER BY created_at DESC
`

type ListDocumentsByOwnerRow struct {
	ID        string
	OwnerID   string
	Title     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListDocumentsByOwner(ctx context.Context, ownerID string) ([]ListDocumentsByOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsByOwnerRow
	for rows.Next() {
		var i ListDocumentsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDocument = `-- name: UpsertDocument :exec
INSERT INTO documents (id, owner_id, title, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE
    SET title      = EXCLUDED.title,
        updated_at = EXCLUDED.updated_at
`

type UpsertDocumentParams struct {
	ID        string
	OwnerID   string
	Title     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) error {
	_, err := q.db.ExecContext(ctx, upsertDocument,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
