// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgstore

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type PfpPreset string

const (
	PfpPresetBlue   PfpPreset = "blue"
	PfpPresetGreen  PfpPreset = "green"
	PfpPresetRed    PfpPreset = "red"
	PfpPresetYellow PfpPreset = "yellow"
	PfpPresetPurple PfpPreset = "purple"
	PfpPresetOrange PfpPreset = "orange"
)

func (e *PfpPreset) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PfpPreset(s)
	case string:
		*e = PfpPreset(s)
	default:
		return fmt.Errorf("unsupported scan type for PfpPreset: %T", src)
	}
	return nil
}

type NullPfpPreset struct {
	PfpPreset PfpPreset
	Valid     bool // Valid is true if PfpPreset is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPfpPreset) Scan(value interface{}) error {
	if value == nil {
		ns.PfpPreset, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PfpPreset.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPfpPreset) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PfpPreset), nil
}

type ShareMode string

const (
	ShareModePrivate ShareMode = "private"
	ShareModeRead    ShareMode = "read"
	ShareModeEdit    ShareMode = "edit"
)

func (e *ShareMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShareMode(s)
	case string:
		*e = ShareMode(s)
	default:
		return fmt.Errorf("unsupported scan type for ShareMode: %T", src)
	}
	return nil
}

type NullShareMode struct {
	ShareMode ShareMode
	Valid     bool // Valid is true if ShareMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShareMode) Scan(value interface{}) error {
	if value == nil {
		ns.ShareMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShareMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShareMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShareMode), nil
}

type Document struct {
	ID        string
	OwnerID   string
	Title     string
	ShareMode string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Operation struct {
	ID         string
	DocumentID string
	Kind       string
	CharOffset int32
	Length     int32
	Text       string
	Version    int64
	CreatedAt  time.Time
}

type Session struct {
	ID               string
	UserID           string
	RefreshTokenHash string
	CreatedAt        time.Time
	ExpiresAt        time.Time
}

type User struct {
	ID           string
	Name         string
	Email        string
	Username     string
	PasswordHash string
	Pfp          string
	CreatedAt    time.Time
}
