// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations.sql

package pgstore

import (
	"context"
	"time"
)

const appendOperation = `-- name: AppendOperation :exec
WITH next_v AS (
    SELECT COALESCE(MAX(version), 0) + 1 AS v
    FROM operations
    WHERE document_id = $2
)
INSERT INTO operations (id, document_id, kind, char_offset, length, text, version, created_at)
SELECT $1, $2, $3, $4, $5, $6, v, $7
FROM next_v
`

type AppendOperationParams struct {
	ID         string
	DocumentID string
	Kind       string
	CharOffset int32
	Length     int32
	Text       string
	CreatedAt  time.Time
}

func (q *Queries) AppendOperation(ctx context.Context, arg AppendOperationParams) error {
	_, err := q.db.ExecContext(ctx, appendOperation,
		arg.ID,
		arg.DocumentID,
		arg.Kind,
		arg.CharOffset,
		arg.Length,
		arg.Text,
		arg.CreatedAt,
	)
	return err
}

const listOperations = `-- name: ListOperations :many
SELECT id, kind, char_offset, length, text, created_at
FROM operations
WHERE document_id = $1
ORDER BY version ASC
`

type ListOperationsRow struct {
	ID         string
	Kind       string
	CharOffset int32
	Length     int32
	Text       string
	CreatedAt  time.Time
}

func (q *Queries) ListOperations(ctx context.Context, documentID string) ([]ListOperationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOperations, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOperationsRow
	for rows.Next() {
		var i ListOperationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.CharOffset,
			&i.Length,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
