// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package pgstore

import (
	"context"
	"time"
)

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO sessions (user_id, refresh_token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, refresh_token_hash, created_at, expires_at
`

type CreateAuthSessionParams struct {
	UserID           string
	RefreshTokenHash string
	ExpiresAt        time.Time
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createAuthSession, arg.UserID, arg.RefreshTokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getAuthSessionByTokenHash = `-- name: GetAuthSessionByTokenHash :one
SELECT id, user_id, refresh_token_hash, created_at, expires_at
FROM sessions
WHERE refresh_token_hash = $1
`

func (q *Queries) GetAuthSessionByTokenHash(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getAuthSessionByTokenHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteAuthSession = `-- name: DeleteAuthSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteAuthSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAuthSession, id)
	return err
}

const deleteAuthSessionByTokenHash = `-- name: DeleteAuthSessionByTokenHash :exec
DELETE FROM sessions WHERE refresh_token_hash = $1
`

func (q *Queries) DeleteAuthSessionByTokenHash(ctx context.Context, refreshTokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteAuthSessionByTokenHash, refreshTokenHash)
	return err
}
