// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package pgstore

import (
	"context"
	"time"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, username, password_hash, pfp, created_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           string
	Name         string
	Email        string
	Username     string
	PasswordHash string
	Pfp          string
	CreatedAt    time.Time
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Pfp,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, username, password_hash, pfp)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, username, pfp, created_at
`

type CreateUserParams struct {
	Name         string
	Email        string
	Username     string
	PasswordHash string
	Pfp          string
}

type CreateUserRow struct {
	ID        string
	Name      string
	Email     string
	Username  string
	Pfp       string
	CreatedAt time.Time
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, username, pfp, created_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID        string
	Name      string
	Email     string
	Username  string
	Pfp       string
	CreatedAt time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.Pfp,
		&i.CreatedAt,
	)
	return i, err
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.Pfp,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.Pfp,
		&i.CreatedAt,
	)
	return i, err
}
