// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package pgstore

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, username, password_hash, pfp)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, username, pfp, created_at
`

type CreateUserParams struct {
	Name         string
	Email        string
	Username     string
	PasswordHash string
	Pfp          string
}

type CreateUserRow struct {
	ID        string
	Name      string
	Email     string
	Username  string
	Pfp       string
	CreatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.Pfp,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.Pfp,
		&i.CreatedAt,
	)
	return i, err
}
